name: Initialize build environment
description: >-
  Prepares a Python build environment with `uv`.

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        version: "0.11.12"

    - name: Setup Python environment
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"

    - name: Install Python dependencies
      shell: bash
      run: |
        uv sync --locked --all-groups
