name: Run checks
description: >-
  Runs validations and linters.

runs:
  using: "composite"
  steps:
    - name: Type check code with mypy
      shell: bash
      run: |
        uv run mypy .

    - name: Validate code with linters
      shell: bash
      run: |
        uv run ruff check

    - name: Lint Dockerfile with Checkov
      uses: bridgecrewio/checkov-action@444c9db6fa75e2d9c19ebf1fde7322089be9009e # v12.3125.0
      with:
        file: ./Dockerfile
        quiet: true
        output_format: cli
        output_file_path: console
