name: Run checks
description: >-
  Runs validations and linters.

runs:
  using: "composite"
  steps:
    - name: Type check code with mypy
      shell: bash
      run: |
        uv run mypy .

    - name: Validate code with linters
      shell: bash
      run: |
        uv run ruff check

    - name: Lint Dockerfile with Checkov
      uses: bridgecrewio/checkov-action@360818f2ad44468d3294cfddae854a8c9036dfee # v12.3014.0 / 3.2.406
      with:
        file: ./Dockerfile
        quiet: true
        output_format: cli
        output_file_path: console
