name: Run checks
description: >-
  Runs validations and linters.

runs:
  using: "composite"
  steps:
    - name: Type check code with mypy
      shell: bash
      run: |
        uv run mypy .

    - name: Validate code with linters
      shell: bash
      run: |
        uv run ruff check

    - name: Lint Dockerfile with Checkov
      uses: bridgecrewio/checkov-action@eec884fd62682f5f2b33e303e160d5e2fe8d89ec # v12.3052.0
      with:
        file: ./Dockerfile
        quiet: true
        output_format: cli
        output_file_path: console
