name: Run checks
description: >-
  Runs validations and linters.

runs:
  using: "composite"
  steps:
    - name: Type check code with mypy
      shell: bash
      run: |
        uv run mypy .

    - name: Validate code with linters
      shell: bash
      run: |
        uv run ruff check

    - name: Lint Dockerfile with Checkov
      uses: bridgecrewio/checkov-action@66cb7d1a5d82e11edf60ee12d465423dbac41916 # v12.3006.0 / 3.2.406
      with:
        file: ./Dockerfile
        quiet: true
        output_format: cli
        output_file_path: console
