name: Initialize Docker environment
description: >-
  Logs into Docker Hub and prepares a multi-platform build environment with BuildKit (buildx)

inputs:
  docker-hub-user:
    description: The user name of the Docker Hub credentials
    required: true
  docker-hub-pass:
    description: The password of the Docker Hub credentials
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-hub-user }}
        password: ${{ inputs.docker-hub-pass }}

    - name: Set up QEMU for multi-platform Docker builds with BuildKit (buildx)
      id: setup-qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
        image: tonistiigi/binfmt@sha256:46c5a036f13b8ad845d6703d38f8cce6dd7c0a1e4d42ac80792279cabaeff7fb # qemu-v8.1.5

    - name: Set up Docker BuildKit (buildx)
      uses: docker/setup-buildx-action@v3
