name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        id: set-version
        uses: ./.github/actions/set-version

      - name: Initialize Docker environment
        uses: ./.github/actions/init-docker
        with:
          docker-hub-user: "${{ vars.DOCKER_HUB_USER }}"
          docker-hub-pass: "${{ secrets.DOCKER_HUB_PASS }}"

      - name: Build and publish Docker image
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          file: ./Dockerfile
          load: false
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            ${{ vars.DOCKER_IMAGE_NAME }}:${{ steps.set-version.outputs.version }}

      - name: Create GitHub Release
        run: |
          curl -fsSL \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name": "${{ steps.set-version.outputs.version }}"
            }'
